apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: seatbooking-app
    name: api-gateway
spec:
  selector:
    app: seatbooking-app
    name: api-gateway-pod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: seatbooking-app
    name: api-gateway
spec:
  selector:
    matchLabels:
      app: seatbooking-app
      name: api-gateway-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: api-gateway-pod
      labels:
        app: seatbooking-app
        name: api-gateway-pod
    spec:
      containers:
        - name: api-gateway-container
          image: dhamodaran/api_gateway:test
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 4500          
          env:
            - name: NODE_ENV
              value: production
            