name: Publish the Stage
on:
  pull_request:
    branches: ["production"]
    types: ["closed"]
env:
  IMG_NAME: api_gateway
jobs:
  build_docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: tag from latest to stable
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMG_NAME }}:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMG_NAME }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMG_NAME }}:stable
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMG_NAME }}:stable
      - name: Image published as Stable
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMG_NAME }}:stable
